### PR TITLE
ATM application using C++

### PR DESCRIPTION
**Pull request by Chandana-23**

### CODE REVIEW

**Comment by officialkushagragupta** [comment]
Can I work on this? I will provide a clean code, more options, and better segregation.

**Comment by Chandana-23** [comment]
Yes,  you may.

Chandana Samineni

**Comment by Chandana-23** [comment]
@officialkushagragupta Would like to contribute or I will close this.

**Comment by officialkushagragupta** [comment]
I have already done it. Kindly review it and merge. 

Regards
Kushagra Gupta

**Review by Chandana-23 — COMMENTED** [review]
Nice work!

**Pull request closed without merging**
